name: Update Spotify Song

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Requests
      run: pip install requests

    - name: Run update script
      run: python scripts/update_spotify.py

    - name: Commit & Push
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add public/data/spotify.json
        git commit -m "Auto-update Spotify track"
        git push
